### ISSUE TITLE
error when running windows and Linux

### ISSUE THREAD

**Issue by mupsje** [niall-oc/pythonta#2]
Hi there, I followed youtube but did not worked out on windows and also linux getting error.
Also I cannot find these 2 yaml files anymore yahoo and binance....

what i'm doing wrong?
(i'm a newbie on python) 

Greets Remco

WINDOWS 
```
C:\Users\Remco\PI\Markets\pythonta-main>python pattern_scanner.py binance_scanner.yaml
Traceback (most recent call last):
  File "C:\Users\Remco\PI\Markets\pythonta-main\pattern_scanner.py", line 148, in <module>
    configuration = handle_args()
  File "C:\Users\Remco\PI\Markets\pythonta-main\pattern_scanner.py", line 47, in handle_args
    configuration  = yaml.load(open(args.config, "r"), Loader=yaml.FullLoader)
FileNotFoundError: [Errno 2] No such file or directory: 'binance_scanner.yaml'
```

LINUX/DEBIAN
```
remco@debian:~/Markets/pythonta$ python3 pattern_scanner.py binance_scanner.yaml --interval 1h
Traceback (most recent call last):
  File "/home/remco/Markets/pythonta/pattern_scanner.py", line 148, in <module>
    configuration = handle_args()
  File "/home/remco/Markets/pythonta/pattern_scanner.py", line 47, in handle_args
    configuration  = yaml.load(open(args.config, "r"), Loader=yaml.FullLoader)
FileNotFoundError: [Errno 2] No such file or directory: 'binance_scanner.yaml'
remco@debian:~/Markets/pythonta$ 
```

**Comment by mupsje** [comment]
Found it ;)

**Comment by niall-oc** [comment]
Apologies yes.  I need to make a new video.  Thanks for your patience
